const data =[
    {id: 1,
    image:"/pizzaimzge/appetizers-individual.jpg ",
    title:"malai boti pizza",
    description:"Malai Boti Pizza” is a fusion of Pakistani and Italian cuisine, with tender chunks of marinated malai boti on top of a delicious pizza crust.",
    price:1080},

    {id: 2,
        image:"/pizzaimzge/arabicpizza.jpg ",
        title:"kabab stuffer pizza",
        description:"A unique fusion of Pakistani and Italian cuisine. of marinated malai boti on top of a delicious pizza crust.",
        price:1250},

        {id: 3,
            image:"/pizzaimzge/121appetizer-box.jpg ",
            title:"pizza sandwich",
            description:"A mouthwatering fusion of pizza and sandwich, with cheese, sauce,",
            price:650},

            {id: 4,
                image:"/pizzaimzge/premium-deal-2.jpg ",
                title:"flaming pasta",
                description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                price:650},
                {id: 5,
                    image:"/pizzaimzge/mamamiaclassic123.jpg ",
                    title:"Chicken fajita pizza",
                    description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                    price:800},
                    {id: 6,
                        image:"/pizzaimzge/lunch-craving-deal-3.jpg  ",
                        title:"BBQ Tikka pizza",
                        description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                        price:800},
                        {id: 7,
                            image:"/pizzaimzge/phantom123.jpg  ",
                            title:"plex Special",
                            description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                            price:800},
                            {id:8,
                                image:"/pizzaimzge/pizza.jpg ",
                                title:"special pizza",
                                description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                                price:1200},
                                {id:9,
                                    image:"/pizzaimzge/chicagoboldfold123.jpg ",
                                    title:"tak tak Special",
                                    description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                                    price:1300},
                                    {id: 10,
                                        image:"/pizzaimzge/arabicpizza.jpg ",
                                        title:"EGG Special",
                                        description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                                        price:800},

                                        {id: 11,
                                            image:"/pizzaimzge/chicagoboldfold123.jpg  ",
                                            title:"vegetable pizza",
                                            description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                                            price:900},
                                            {id: 12,
                                                image:"/pizzaimzge/pizza.jpg  ",
                                                title:"Chicken Special",
                                                description:"A fiery and flavorful dish with pasta, spicy sauce, and flambeed with brandy for a dramatic presentation.",
                                                price:1400},
                                                {
                                                    id:13,
                                                    image:"pizzaimzge/arabicpizza.jpg ",
                                                    title:'Arabic pizza',
                                                    description:"Brand spicy and delecious pizza ",
                                                    price:1250
                                                }

]    
export default data;